### PR TITLE
fix: call PlayerDisconnectEvent on Configuration

### LINKED ISSUE #2242: PlayerDisconnectEvent not called if player in Configuration
image
image

### PR DESCRIPTION
**Pull request by Spliterash**
If the player was disconnected during configuration, the PlayerDisconnectEvent event will not be thrown. Even though PlayerConnection calls `player.scheduleNextTick(Entity::remove);`, it will never be executed because the player is not ticked off

resolves #2242

### CODE REVIEW

**Review by mworzala — COMMENTED** [review]
I believe `isSpawned` is unnecessary. You can check the state of the player during the event to see if they are preplay when being disconnected.

**Comment by MelonHell** [comment]
What else is missing in order to complete this pull request?

File: src/main/java/net/minestom/server/network/player/PlayerConnection.java [hunk 1]
```diff
@@ -119,8 +121,12 @@ public void disconnect() {
         this.online = false;
         MinecraftServer.getConnectionManager().removePlayer(this);
         final Player player = getPlayer();
-        if (player != null && !player.isRemoved()) {
-            player.scheduleNextTick(Entity::remove);
+        if (player != null) {
+            if (connectionState == ConnectionState.PLAY && !player.isRemoved())
+                player.scheduleNextTick(Entity::remove);
+            else {
+                EventDispatcher.call(new PlayerDisconnectEvent(player));
```
Comment (mworzala) [inline src/main/java/net/minestom/server/network/player/PlayerConnection.java:128]: This should only be called if player is not removed, and should call remove itself. Currently if 3 different handlers of `AsyncPlayerConfigurationEvent` kicked the player, `PlayerDisconnectEvent` would be called 3 times.

**Comment by Andrei965** [comment]
What else needs to be done for this to get merged?
