### PR TITLE
fix: Ignored empty compound serialisation flag

### LINKED ISSUE #2912: [Bug]: Empty compound missing when reading a tag
### Affected Version

2025.09.13-1.21.8, latest git version

### Describe the bug

Even when setting the `SERIALIZE_EMPTY_COMPOUND` server flag to true, when a TagHandler is read from an NBT compound, any empty compounds inside are absent when reading a tag of type NBT, 
e.g. for the custom data component from an item
`{"test": {"type": "something", value: {}}}`

Reading `Tag.NBT("test")` gives `{"type": "something"}`, missing the empty `value` compound, despite being present on the NBT

### Steps to reproduce the bug

_No response_

### Code sample

```java
    @Test
    public void emptyCompound() {
        var tag = Tag.NBT("test");

        var handler = TagHandler.newHandler();
        var value = CompoundBinaryTag.builder()
                .putString("type", "something")
                .put("value", CompoundBinaryTag.empty())
                .build();
        handler.setTag(tag, value);

        var nbt = handler.asCompound();
        var newHandler = TagHandler.fromCompound(nbt);
        assertEquals(value, newHandler.getTag(tag));
    }
```

### PR DESCRIPTION
**Pull request by SorkoPiko**
## Proposed changes

Fixes a logic issue in the `TagHandlerImpl.Node` class. It now properly acknowledges the `SERIALIZE_EMPTY_COMPOUND` flag. Fixes #2912.

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: src/main/java/net/minestom/server/tag/TagHandlerImpl.java [hunk 1]
```diff
@@ -281,7 +281,7 @@ CompoundBinaryTag compound() {
                 this.entries.forValues(entry -> {
                     final Tag tag = entry.tag;
                     final BinaryTag nbt = entry.updatedNbt();
-                    if (nbt != null && (!tag.entry.isPath() || (!ServerFlag.SERIALIZE_EMPTY_COMPOUND) && ((CompoundBinaryTag) nbt).size() > 0)) {
+                    if (nbt != null && (!tag.entry.isPath() || ServerFlag.SERIALIZE_EMPTY_COMPOUND || !((CompoundBinaryTag) nbt).isEmpty())) {
```
Comment (kermandev) [inline src/main/java/net/minestom/server/tag/TagHandlerImpl.java:284]: Doesnt seem to fix the issue outlined, using the provided test it still ignores the empty compound.

Comment (SorkoPiko) [reply src/main/java/net/minestom/server/tag/TagHandlerImpl.java:284]: that's strange, i don't know how it worked for me. i'll take a look, thanks 👍

File: src/main/java/net/minestom/server/tag/TagNbtSeparator.java [hunk 2]
```diff
@@ -53,10 +53,16 @@ private static void convert(List<String> path, String key, BinaryTag nbt, Consum
             Tag tag = tagFunction.apply(key);
             consumer.accept(makeEntry(path, tag, BinaryTagUtil.nbtValueFromTag(nbt)));
         } else if (nbt instanceof CompoundBinaryTag nbtCompound) {
-            for (var ent : nbtCompound) {
-                var newPath = new ArrayList<>(path);
-                newPath.add(key);
-                convert(newPath, ent.getKey(), ent.getValue(), consumer);
+            if (nbtCompound.isEmpty()) {
+                if (net.minestom.server.ServerFlag.SERIALIZE_EMPTY_COMPOUND || path.isEmpty()) {
```
Comment (kermandev) [inline src/main/java/net/minestom/server/tag/TagNbtSeparator.java]: Please import ServerFlag

**Review by kermandev — CHANGES_REQUESTED** [review]
Thanks, seems to fix the issue. 

In the future Minestom will likely convert server flags into feature flags in tests under the server process if applicable. Until then this is fine.

File: src/main/java/net/minestom/server/tag/TagNbtSeparator.java (hunk 2 above)
Comment (SorkoPiko) [reply src/main/java/net/minestom/server/tag/TagNbtSeparator.java]: sorry, i didn't notice that. 👍🏻

**Review by kermandev — APPROVED** [review]
